# Generated by Django 3.0.5 on 2020-06-06 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(default='', max_length=300, null=True)),
                ('category', models.CharField(default='', max_length=30)),
                ('makerName', models.CharField(default='', max_length=50, null=True)),
                ('photoUrl', models.CharField(max_length=500)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('publishedYn', models.BooleanField(default=0)),
                ('achievementRate', models.IntegerField(default=0)),
                ('totalAmount', models.IntegerField(default=0)),
                ('totalSupporter', models.IntegerField(default=0)),
                ('totalLike', models.IntegerField(default=0)),
                ('endYn', models.BooleanField(default=False)),
                ('detailUrl', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('contents', models.CharField(max_length=300)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
