# Generated by Django 3.0.5 on 2020-06-06 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_commentproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentProduct',
            new_name='Comment',
        ),
    ]
